import prisma from '@/lib/prisma'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { CheckCircle2, Circle } from 'lucide-react'

export default async function TasksPage({
  params,
}: {
  params: Promise<{ workspaceId: string }>
}) {
  const { workspaceId } = await params
  
  const tasks = await prisma.task.findMany({
    where: { workspaceId },
    orderBy: { createdAt: 'desc' }
  })

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-3xl font-semibold tracking-tighter">Tasks</h2>
        <p className="text-muted-foreground">
          Tasks generated by the AI assistant.
        </p>
      </div>

      <div className="grid gap-4">
        {tasks.length === 0 ? (
          <Card className="flex flex-col items-center justify-center p-12 text-center border-dashed">
            <CardTitle className="mb-2">No tasks yet</CardTitle>
            <CardDescription>
              Ask the AI assistant to create a task for you using the &quot;save_task&quot; tool.
            </CardDescription>
          </Card>
        ) : (
          tasks.map(task => (
            <Card key={task.id} className={task.completed ? 'opacity-70' : ''}>
              <CardContent className="flex items-start gap-4 p-4">
                <div className="mt-1">
                  {task.completed ? (
                    <CheckCircle2 className="h-5 w-5 text-primary" />
                  ) : (
                    <Circle className="h-5 w-5 text-muted-foreground" />
                  )}
                </div>
                <div className="flex-1">
                  <div className="flex items-center justify-between">
                    <p className={`font-medium ${task.completed ? 'line-through text-muted-foreground' : ''}`}>
                      {task.title}
                    </p>
                    <span className="text-xs text-muted-foreground">
                      {new Date(task.createdAt).toLocaleDateString()}
                    </span>
                  </div>
                  {task.description && (
                    <p className="text-sm text-muted-foreground mt-1">
                      {task.description}
                    </p>
                  )}
                </div>
              </CardContent>
            </Card>
          ))
        )}
      </div>
    </div>
  )
}
